# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./

# Install dependencies without running prepare scripts (we'll run build separately)
RUN npm ci --ignore-scripts

# Build the project
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Expose any port if needed (MCP typically communicates over stdio, not TCP)

# Run the built server
CMD [ "node", "dist/index.js" ]
